name: JohnHasson
favicon: null
layout_spectrum: 0.35353
typography_spectrum: 0.86344
title: John Hasson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-345490-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8f8f8f'
    - '#881280'
    - '#5a5a5a'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
